spring:
  application:
    name: w-ai-code-mother-backend

server:
  port: 8123
  servlet:
    context-path: /api
    # cookie 30天过期 [前端的过期]
    session:
      cookie:
        max-age: 259200

# springdoc-openapi项目配置
springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.wjp.waicodemotherbackend.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn

