spring:
  application:
    name: w-ai-code-mother-backend

  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/w_ai_code_mother
    username: root
    password: 123456
  profiles:
    # 生效配置【读取application-loca.yml中的配置】
    active: local

server:
  port: 8123
  servlet:
    context-path: /api
    # cookie 30天过期 [前端的过期]
    session:
      cookie:
        max-age: 259200

# springdoc-openapi项目配置
springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.wjp.waicodemotherbackend.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn

